# Copyright (c) 2025, The Isaac Lab Arena Project Developers (https://github.com/isaac-sim/IsaacLab-Arena/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

version: 2
workflow:
  name: {{ workflow_name }}
  groups:
  - name: finetune
    tasks:
    - args:
      - /tmp/entry.sh
      command:
      - bash
      credentials:
        wandb-auth:
          WANDB_API_KEY: wandb_pass
      downloadType: download
      environment:
        ACCEPT_EULA: Y
        NO_NUCLEUS: Y
      files:
      - contents: |-
          set -euxo pipefail

          # Run filebrowser to access intermediate checkpoints.
          filebrowser -r / &

          echo "The contents of the input OSMO dataset:"
          ls {{input:0}}/{{input_dataset_name}}

          # Display info on the system
          nvidia-smi
          cd /workspace

          # List the contents of the dataset
          echo "The contents of the lerobot directory:"
          ls {{input:0}}/{{input_dataset_name}}/{{input_demo_name}}/lerobot

          # Set the WANDB_NAME environment variable
          # Weights and Biases naming
          export WANDB_ENTITY=nv-welcome
          export WANDB_PROJECT="Isaac Lab Arena"
          export WANDB_NAME="{{ workflow_name }}_$(date +%Y%m%d_%H%M%S)"

          # Modify gr00t code to allow for naming of the run.
          sed -i "s/^\(\s*run_name=\)None/\1\"${WANDB_NAME}\"/" scripts/gr00t_finetune.py

          # Launch finetune
          HYDRA_FULL_ERROR=1 python scripts/gr00t_finetune.py \
            --dataset_path="{{input:0}}/{{input_dataset_name}}/{{input_demo_name}}/lerobot" \
            --output_dir={{output}} \
            --data_config={{ data_config }} \
            --batch_size={{ batch_size }} \
            --max_steps={{ max_steps }} \
            --num_gpus={{ gpus }} \
            --save_steps=5000 \
            --base_model_path=/workspace/pretrained_ckpts/GR00T-N1.5-3B \
            --no-tune_llm  \
            --tune_visual \
            --tune_projector \
            --tune_diffusion_model \
            --no-resume \
            --dataloader_num_workers=16 \
            --report_to=wandb \
            --embodiment_tag={{ embodiment_tag }} \
            --lora_rank={{ lora_rank }}

          # kill the filebrowser process
          kill $(pgrep -f browser)
        path: /tmp/entry.sh
      image: nvcr.io/nvidian/gr00t_gn15:latest@sha256:8ed83caf3c08a2602bbda0f5648401194ff24ea59ebf456208a8240d750f6aa7
      inputs:
      - dataset:
          name: isaac/{{ input_dataset_name }}
      lead: true
      name: master
      outputs:
      - url: swift://pdx.s8k.io/AUTH_team-isaac/mimic/datasets/{{workflow_id}}
  resources:
    default:
      cpu: {{ cpus }}
      gpu: {{ gpus }}
      memory: 700Gi
      platform: ovx-l40
      storage: 400Gi
  timeout:
    exec_timeout: 7d
    queue_timeout: 2d

default-values:
  cpus: 60
  gpus: 8
  batch_size: 24
  lora_rank: 0
  max_steps: 20000
  # Static manipulation
  # workflow_name: gr1_open_microwave_kitchen
  # input_dataset_name: lerobot_gr1
  # input_demo_name: gr1_open_microwave_50_generated
  # embodiment_tag: gr1
  # data_config: fourier_gr1_arms_only
  # Locomanipulation
  workflow_name: g1_move_box_galileo
  input_dataset_name: lerobot_g1
  input_demo_name: arena_g1_loco_manipulation_dataset_generated
  embodiment_tag: new_embodiment
  data_config: unitree_g1_sim_wbc
